[features]
seeds = true
skip-lint = false

[programs.localnet]
token_program = "32d7pdBNmDmXAXcHkivteqLjaNVovWQ1JMn85LdyyAux"
wrapper_program = "F96CHxPDRgjUypdUqpJocgT59vEPT79AFJXjtyPCBaRt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/noahgundotra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

# Token Metadata Program
[[test.validator.clone]]
url = "https://api.mainnet-beta.solana.com"
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# pNFT Ruleset Program
[[test.validator.clone]]
url = "https://api.mainnet-beta.solana.com"
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"

# pNFT Ruleset Program - Metaplex Foundation Rule Set (created by Brandon Tulsi of Metaplex, default rule set, all pass-through rules)
[[test.validator.clone]]
url = "https://api.mainnet-beta.solana.com"
address = "eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9"