[features]
seeds = true
skip-lint = false

[programs.localnet]
token_program = "32d7pdBNmDmXAXcHkivteqLjaNVovWQ1JMn85LdyyAux"
wrapper_program = "F96CHxPDRgjUypdUqpJocgT59vEPT79AFJXjtyPCBaRt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/noahgundotra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
